### ISSUE TITLE
Frontend: Error on HistoryView

### ISSUE THREAD

**Issue by petertrr** [analysis-dev/save-cloud#576]
After #570 there is an error when loading `HistoryView`:
```
VM520 react_devtools_backend.js:4061 TypeError: Cannot read properties of undefined (reading 'id')
    at oc.doResume (save-frontend.js:1:1554010)
    at Oa.local$closure$getData (save-frontend.js:1:1555730)
    at Oa.doResume (save-frontend.js:1:1513125)
    at Oa.Cn.resumeWith_tl1gpc$ (save-frontend.js:1:585805)
    at Nn.Ln.run (save-frontend.js:1:893679)
    at fr.mr.process (save-frontend.js:1:923778)
    at save-frontend.js:1:923355
```

**Comment by petertrr** [comment]
Another error after #570: preprocessor cannot deserialize `LocalDateTime` from `Organization` in `ExecutionRequest`
