### ISSUE TITLE
Bug with serialization during rerun

### ISSUE THREAD

**Issue by kgevorkyan** [analysis-dev/save-cloud#732]
In process of communication between backend and preprocessor there is occurred exception corresponding the serialization:

```bash
14:14:54.502 [reactor-http-epoll-4] INFO o.c.s.p.c.DownloadProjectController - Making request to update execution with id=23
14:49:08.095 [reactor-http-epoll-2] ERROR o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler - [e66ed0b1-4]  500 Server Error for HTTP POST "/rerunExecution?executionType=STANDARD"
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 232: Expected beginning of the string, but got [
JSON input: .....ei","ownerId":1,"dateCreated":[2021,1,1,0,0],"avatar":null,".....
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        *__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP POST "/rerunExecution?executionType=STANDARD" [ExceptionHandlingWebHandler]Original Stack Trace:
                at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
15:22:11.620 [reactor-http-epoll-2] ERROR o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler - [e66ed0b1-5]  500 Server Error for HTTP POST "/rerunExecution?executionType=STANDARD"> 90% EXECUTING [37m 48s]n.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:524)
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 232: Expected beginning of the string, but got [
JSON input: .....ei","ownerId":1,"dateCreated":[2021,1,1,0,0],"avatar":null,".....ringLenient(AbstractJsonLexer.kt:394)
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)kt:201)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: extToken(StringJsonLexer.kt:74)
Error has been observed at the following site(s):ernal.StringJsonLexer.consumeKeyString(StringJsonLexer.kt:85)
        *__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP POST "/rerunExecution?executionType=STANDARD" [ExceptionHandlingWebHandler]coder.kt:256)
Original Stack Trace:tlinx.datetime.serializers.LocalDateTimeIso8601Serializer.deserialize(LocalDateTimeSerializers.kt:19)
```

Again in `LocalDateTimeSerializers`, despite the fact, that we have some configs for LocalDateTime Serialization in preprocessor

**Comment by petertrr** [comment]
I believe in #587 we switched Jackson serialization to ISO-formatted string instead of arrays, but here JSON input contains array. Maybe, there is some ObjectMapper with incorrect configuration?

**Comment by akuleshov7** [comment]
dateCreated is expected to be String, but you receive incorrect serialization done by Jackson (array)
